version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13 # PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: user # Define your database user
      POSTGRES_PASSWORD: password # Define your database user's password
      POSTGRES_DB: mydb # Define the name of the database
    ports:
      - '5432:5432' # PostgreSQL default port
    volumes:
      - db-data:/var/lib/postgresql/data # Data persistence

volumes:
  db-data:
